/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sputniks.workshop_kafka_train.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TrainPosition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3229535714038748385L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TrainPosition\",\"namespace\":\"com.sputniks.workshop_kafka_train.avro\",\"fields\":[{\"name\":\"trainId\",\"type\":\"string\"},{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"},{\"name\":\"speedKph\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TrainPosition> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TrainPosition> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TrainPosition> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TrainPosition> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TrainPosition> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TrainPosition to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TrainPosition from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TrainPosition instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TrainPosition fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence trainId;
  private double latitude;
  private double longitude;
  private int speedKph;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TrainPosition() {}

  /**
   * All-args constructor.
   * @param trainId The new value for trainId
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param speedKph The new value for speedKph
   */
  public TrainPosition(java.lang.CharSequence trainId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Integer speedKph) {
    this.trainId = trainId;
    this.latitude = latitude;
    this.longitude = longitude;
    this.speedKph = speedKph;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return trainId;
    case 1: return latitude;
    case 2: return longitude;
    case 3: return speedKph;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: trainId = (java.lang.CharSequence)value$; break;
    case 1: latitude = (java.lang.Double)value$; break;
    case 2: longitude = (java.lang.Double)value$; break;
    case 3: speedKph = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'trainId' field.
   * @return The value of the 'trainId' field.
   */
  public java.lang.CharSequence getTrainId() {
    return trainId;
  }


  /**
   * Sets the value of the 'trainId' field.
   * @param value the value to set.
   */
  public void setTrainId(java.lang.CharSequence value) {
    this.trainId = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'speedKph' field.
   * @return The value of the 'speedKph' field.
   */
  public int getSpeedKph() {
    return speedKph;
  }


  /**
   * Sets the value of the 'speedKph' field.
   * @param value the value to set.
   */
  public void setSpeedKph(int value) {
    this.speedKph = value;
  }

  /**
   * Creates a new TrainPosition RecordBuilder.
   * @return A new TrainPosition RecordBuilder
   */
  public static com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder newBuilder() {
    return new com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder();
  }

  /**
   * Creates a new TrainPosition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TrainPosition RecordBuilder
   */
  public static com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder newBuilder(com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder other) {
    if (other == null) {
      return new com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder();
    } else {
      return new com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder(other);
    }
  }

  /**
   * Creates a new TrainPosition RecordBuilder by copying an existing TrainPosition instance.
   * @param other The existing instance to copy.
   * @return A new TrainPosition RecordBuilder
   */
  public static com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder newBuilder(com.sputniks.workshop_kafka_train.avro.TrainPosition other) {
    if (other == null) {
      return new com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder();
    } else {
      return new com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder(other);
    }
  }

  /**
   * RecordBuilder for TrainPosition instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TrainPosition>
    implements org.apache.avro.data.RecordBuilder<TrainPosition> {

    private java.lang.CharSequence trainId;
    private double latitude;
    private double longitude;
    private int speedKph;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.trainId)) {
        this.trainId = data().deepCopy(fields()[0].schema(), other.trainId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.speedKph)) {
        this.speedKph = data().deepCopy(fields()[3].schema(), other.speedKph);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TrainPosition instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sputniks.workshop_kafka_train.avro.TrainPosition other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.trainId)) {
        this.trainId = data().deepCopy(fields()[0].schema(), other.trainId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.speedKph)) {
        this.speedKph = data().deepCopy(fields()[3].schema(), other.speedKph);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'trainId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTrainId() {
      return trainId;
    }


    /**
      * Sets the value of the 'trainId' field.
      * @param value The value of 'trainId'.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder setTrainId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.trainId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'trainId' field has been set.
      * @return True if the 'trainId' field has been set, false otherwise.
      */
    public boolean hasTrainId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'trainId' field.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder clearTrainId() {
      trainId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder setLatitude(double value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder clearLatitude() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder setLongitude(double value) {
      validate(fields()[2], value);
      this.longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder clearLongitude() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'speedKph' field.
      * @return The value.
      */
    public int getSpeedKph() {
      return speedKph;
    }


    /**
      * Sets the value of the 'speedKph' field.
      * @param value The value of 'speedKph'.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder setSpeedKph(int value) {
      validate(fields()[3], value);
      this.speedKph = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'speedKph' field has been set.
      * @return True if the 'speedKph' field has been set, false otherwise.
      */
    public boolean hasSpeedKph() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'speedKph' field.
      * @return This builder.
      */
    public com.sputniks.workshop_kafka_train.avro.TrainPosition.Builder clearSpeedKph() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TrainPosition build() {
      try {
        TrainPosition record = new TrainPosition();
        record.trainId = fieldSetFlags()[0] ? this.trainId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.Double) defaultValue(fields()[1]);
        record.longitude = fieldSetFlags()[2] ? this.longitude : (java.lang.Double) defaultValue(fields()[2]);
        record.speedKph = fieldSetFlags()[3] ? this.speedKph : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TrainPosition>
    WRITER$ = (org.apache.avro.io.DatumWriter<TrainPosition>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TrainPosition>
    READER$ = (org.apache.avro.io.DatumReader<TrainPosition>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.trainId);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeInt(this.speedKph);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.trainId = in.readString(this.trainId instanceof Utf8 ? (Utf8)this.trainId : null);

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.speedKph = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.trainId = in.readString(this.trainId instanceof Utf8 ? (Utf8)this.trainId : null);
          break;

        case 1:
          this.latitude = in.readDouble();
          break;

        case 2:
          this.longitude = in.readDouble();
          break;

        case 3:
          this.speedKph = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










