spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Use the Avro Serializer for the value
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        # Point to our local Schema Registry
        schema.registry.url: http://localhost:8081
        # Recommended: Automatically register new schemas
        auto.register.schemas: true